---
     - name: remove apache
       apt:
          name: apache2
          state: absent
     - name: install apache
       apt:
          name: apache2
          state: present
     - name: stop apache service
       service:
          name: apache2
          state: stopped
     - name: start apache service
       service:
          name: apache2
          state: started
    
